spring.application.name=IT210_projectfinal

spring.datasource.url=jdbc:mysql://localhost:3306/smart_healthcare?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=26062006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false
spring.jpa.open-in-view=false
server.port=8080


